### PR TITLE
Adding action.yml

### LINKED ISSUE #2: [warning]Unexpected input 'time', valid inputs are ['']
Using the suggested syntax from the README this action works great (as expected), but GitHub Actions logs always reports a warning:

##[warning]Unexpected input 'time', valid inputs are ['']

Looking around online, it appears this may be a new behavior from Github Actions while it's in beta.

ref: https://github.com/samuelmeuli/lint-action/issues/53
Excerpt from 17 hours ago as of this writing: "I've just gotten the same thing pop up, I was testing this last week and wasn't hitting it, all of a sudden it has appeared."

Not sure what the fix is yet, but it seems likely Github Actions beta will announce a way to specify expected input values, probably resolving this.

### PR DESCRIPTION
**Pull request by aceberle**
Fixes jakejarvis/wait-action#2

### CODE REVIEW

**Comment by aceberle** [comment]
I opened this in case #3 never gets merged

**Comment by lgmorand** [comment]
if jake ignores this PR as this other, we'll be as the same stage :'( 

@jakejarvis you seem active on GH, any reason not to merge the PR? thanks :)

**Comment by joaopgrassi** [comment]
Maybe someone can drop him an email? Maybe he got lost in this, or turned off notifications 😅?

**Comment by lgmorand** [comment]
I sent him an email on 18th April regarding this merge just in case...never got any answer :'(

**Comment by jakejarvis** [comment]
Closing in favor of #4 being merged, deepest apologies again for the colossal delay!

**Pull request closed without merging**
