### PR TITLE
Add metadata to action

### LINKED ISSUE #2: [warning]Unexpected input 'time', valid inputs are ['']
Using the suggested syntax from the README this action works great (as expected), but GitHub Actions logs always reports a warning:

##[warning]Unexpected input 'time', valid inputs are ['']

Looking around online, it appears this may be a new behavior from Github Actions while it's in beta.

ref: https://github.com/samuelmeuli/lint-action/issues/53
Excerpt from 17 hours ago as of this writing: "I've just gotten the same thing pop up, I was testing this last week and wasn't hitting it, all of a sudden it has appeared."

Not sure what the fix is yet, but it seems likely Github Actions beta will announce a way to specify expected input values, probably resolving this.

### PR DESCRIPTION
**Pull request by joaopgrassi**
- Added the required [metadata file](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions)
- Used the same values found in the `Dockerfile`

fixes #2

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@jakejarvis Mind merging/releasing this? 🙂

**Comment by kibertoad** [comment]
@jakejarvis Ping?..

**Comment by clearyusc** [comment]
@jakejarvis please merge!

**Comment by kibertoad** [comment]
@clearyusc @rijkvanzanten I've ended up giving up and publishing my own fork with this fix, you can use it if you want: https://github.com/kibertoad/wait-action

**Comment by drupol** [comment]
Using the fork as well. Thanks !

**Comment by joaopgrassi** [comment]
I ignored notifications on this PR. Will keep it open if the author wants to merge, but I'll probably not respond anymore.

**Comment by lgmorand** [comment]
@jakejarvis  hey buddy :)

**Comment by aceberle** [comment]
This was painful to read through.  @jakejarvis, are you saying that you do not have permission to merge the PR?  If that's true, then @joaopgrassi can you please merge this PR?

**Comment by joaopgrassi** [comment]
@aceberle not sure what you mean? I'm not the owner of this repo, so I can't merge anything :). Also not sure where you saw the owner saying he does not have permission. Maybe another thread?

**Comment by jakejarvis** [comment]
Huge apologies to everybody, I did indeed miss all of these notifications somehow. Gladly merging this in a new release and I'm also adding other sleeping methods to the readme (simply running the `sleep` command in the Bash script, or `Start-Sleep` on Windows where Docker actions can't even be used) which I think makes a lot more sense than using this action.

But if anybody here wants to be added to this repo with push permissions let me know so you don't need to wait another few months for me if you'd like to keep using this and something else pops up! ;)

**Pull request merged**
